"""increase_password_hash_length

Revision ID: 33068e09b0ca
Revises: f2ad8a619ab9
Create Date: 2026-01-07 13:22:02.083527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33068e09b0ca'
down_revision = 'f2ad8a619ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
